Weapons = [{
            "Bastard Word": {"Type:": "M", "Range:": "C", "Damage": "1d8/1d10", "Properties": "V, 2 slots"},
            "Club": {"Type:": "M", "Range:": "C", "Damage": "1d4", "Properties": "None"},
            "Crossbow": {"Type:": "R", "Range:": "F", "Damage": "1d6", "Properties": "2H, L"},
            "Dagger": {"Type:": "M/R", "Range:": "C/N", "Damage": "1d4", "Properties": "F, Th"},
            "Greataxe": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Javelin": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Longbow": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Longsword": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Mace": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Shortbow": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Shortsword": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Spear": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Staff": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            "Warhammer": {"Type:": "", "Range:": "", "Damage": "", "Properties": ""},
            }]
